# -*- coding: utf-8 -*-
"""AVD_Yeheskiel_Darmawan.ipynb.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIBQF8ADiraSvQ7HKBLe_fgwTAxNARFw

Tugas AVD

Nama: Yeheskiel Darmawan

Nim: 2509116027

# **Analisis Faktor yang Mempengaruhi Kinerja dan Retensi Karyawan**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file = "/content/drive/MyDrive/Messy_Employee_dataset.csv"
df = pd.read_csv(file)

df

from google.colab import drive
drive.mount('/content/drive')

"""# **Business Understanding**

Analisis ini dilakukan untuk memahami kondisi karyawan di perusahaan berdasarkan data yang tersedia. Dari dataset tersebut, terlihat bahwa terdapat informasi seperti usia, salary, pengalaman kerja, departemen, dan performance rating yang dapat digunakan untuk melihat pola tertentu. Selain itu, terdapat beberapa data yang masih kosong sehingga perlu diperhatikan sebelum analisis lebih lanjut dilakukan. Melalui analisis ini, diharapkan perusahaan bisa mendapatkan gambaran yang lebih jelas mengenai faktor yang mempengaruhi performa dan keberlangsungan kerja karyawan

## **Business Objective**

Mengetahui faktor yang paling berpengaruh terhadap kinerja dan keputusan karyawan untuk tetap bekerja atau resign, sehingga perusahaan dapat mengambil keputusan yang lebih tepat dalam mengelola SDM

## **Assess Situation**

*   **Ketersediaan Data**
Dataset sudah tersedia dan berisi informasi mengenai usia, salary, pengalaman kerja, departemen, performance rating, dan status kerja karyawan

*   **Kondisi Data**
Dari pengecekan awal, ditemukan beberapa nilai yang kosong pada kolom tertentu seperti Age dan Salary, sehingga perlu dilakukan pembersihan data sebelum analisis lebih lanjut

*   **Kesiapan Analisis**
Secara umum data sudah cukup untuk dilakukan eksplorasi, namun tetap diperlukan tahap persiapan agar hasil analisis lebih akurat dan tidak bias

## **Analytic Goals**

**Tujuan analisis dalam proyek ini adalah:**

* **Mengidentifikasi faktor yang mempengaruhi performance karyawan**
Melihat apakah variabel seperti salary, usia, dan pengalaman kerja memiliki hubungan dengan performance rating

* **Menganalisis pola karyawan yang resign**
Mengamati apakah terdapat karakteristik tertentu pada karyawan yang keluar dibandingkan dengan yang masih aktif

* **Mengevaluasi kesesuaian antara salary dan pengalaman kerja**
Menilai apakah terdapat pola yang menunjukkan hubungan yang wajar antara pengalaman kerja dan tingkat gaji

* **Memberikan gambaran awal berbasis data**
Menyusun hasil analisis sebagai dasar untuk pemahaman kondisi karyawan secara keseluruhan

## **Project Plan**

**Tahapan yang akan dilakukan dalam proyek ini meliputi:**

1.   **Business Understanding**
Memahami latar belakang permasalahan serta tujuan analisis yang ingin dicapai
2.   **Data Understanding**
Melakukan pengecekan awal terhadap struktur dataset, tipe variabel, serta keberadaan nilai yang kosong
1.   **Data Preparation**
Membersihkan dan menyiapkan data agar siap untuk proses analisis selanjutnya
2.   **Exploratory Data Analysis (EDA)**
Melakukan analisis awal untuk melihat pola atau hubungan antar variabel yang berpotensi berpengaruh terhadap kinerja dan status kerja karyawan

# **Checkpoint 2**

# **Data Understanding & Exploratory Data Analysis (EDA)**
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""## **Memuat Dataset**"""

file = '/content/drive/MyDrive/tugas AVD/Messy_Employee_dataset.csv'

df = pd.read_csv(file)
df

"""## **Data Understanding**

## Struktur Data
"""

df.info()

print(df.columns)

"""**Insight**:
- Dataset memiliki sejumlah baris dan kolom
- Beberapa kolom seperti Salary dan Join_Date masih bertipe object
- Perlu penyesuaian tipe data sebelum analisis lebih lanjut

## **Statistik Deskriptif**
"""

df.describe(include='all')

"""**Insight:**
- Terdapat variasi nilai pada kolom numerik
- Kategori pada kolom teks menunjukkan kemungkinan inkonsistensi

## **Cek Tipe Data**
"""

df.dtypes

"""**Insight:**
- Berdasarkan hasil pengecekan tipe data, kolom numerik seperti Age, Work_Experience, dan Salary_num sudah bertipe int/float sehingga siap digunakan untuk analisis statistik.
Kolom Employee_ID, Dept, dan Status bertipe object karena merupakan data kategorikal.
Secara umum, tipe data sudah sesuai dan tidak memerlukan perubahan lebih lanjut.

## **Cek Inconsistent Values**

## **Cek Seluruh Kolom Category**
"""

cols = df.select_dtypes(include='object')

for col in cols:
    print("Kolom :", col)
    print(df[col].unique())

"""**Insight:**

- Technology
- technology
- TECHNOLOGY

## **Missing Values**
"""

pd.DataFrame(df.isna().sum() / len(df) * 100, columns=['Null Ratio in %'])

"""**Insight:**
- Beberapa kolom memiliki missing values yang signifikan.
- Perlu dilakukan imputasi atau pembersihan.

## **Duplicate Values**
"""

df.duplicated().sum()

"""**Insight:**
- Data duplikat dapat mempengaruhi hasil agregasi dan analisis

## **Outliers (Salary)**
"""

df['Salary_num'] = pd.to_numeric(df['Salary'].replace('[\$,]', '', regex=True), errors='coerce')
sns.boxplot(x=df['Salary_num'])
plt.title('Outliers in Salary')
plt.show()

"""**Insight:**
- Terdapat nilai salary ekstrem yang perlu dianalisis lebih lanjut

# **Exploratory Data Analysis (EDA)**

## **Comparison – Average Salary per Department**
"""

plt.figure(figsize=(8,5))

df.groupby('Status')['Salary_num'].mean().sort_values().plot(kind='bar')

plt.title('Average Salary per Status')
plt.xlabel('Status')
plt.ylabel('Average Salary')

plt.show()

"""**Insight:**
- Grafik menunjukkan rata-rata salary berdasarkan status karyawan. Perbedaan rata-rata gaji antar status dapat memberikan gambaran mengenai struktur kompensasi di perusahaan

## **Composition – Employee Status**
"""

df['Status'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title('Komposisi Status Karyawan')
plt.ylabel('')
plt.show()

"""**Insight:**
- Mayoritas karyawan berada pada satu kategori status tertentu

## **Distribution – Age**
"""

plt.figure(figsize=(8,5))
sns.histplot(df['Salary'], kde=True)
plt.title('Distribusi Salary')
plt.xlabel('Salary')
plt.show()

"""**Insight:**
- Distribusi usia menunjukkan pola tertentu dalam populasi karyawan

## **Relationship – Salary vs Performance Score**
"""

sns.boxplot(x='Performance_Score', y='Salary_num', data=df)
plt.title('Salary vs Performance Score')
plt.show()

"""**Insight:**
- Karyawan dengan performa lebih tinggi cenderung memiliki salary lebih tinggi

# **Checkpoint 3**
"""

df.info()
df.describe(include='all')

"""## **Tipe Data**
Kolom tanggal diubah menjadi datetime agar dapat digunakan untuk analisis berbasis waktu.
"""

if 'Join_Date' in df.columns:
    df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors='coerce')

df.info()

"""## **Missing Value**
Missing value numerik diisi menggunakan median karena lebih tahan terhadap outlier.
"""

print('Missing Value Sebelum:')
display(df.isnull().sum())

num_cols = df.select_dtypes(include='number').columns

for col in num_cols:
    median_value = df[col].median()
    print(f'Mengisi {col} dengan median =', median_value)
    df[col] = df[col].fillna(median_value)

"""Kolom kategorikal diisi menggunakan modus untuk mempertahankan kategori dominan."""

cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    mode_value = df[col].mode()[0]
    df[col] = df[col].fillna(mode_value)

print('Missing Value Sesudah:')
display(df.isnull().sum())

"""## **Inconsistent Values**
Standardisasi teks dilakukan agar tidak terjadi perbedaan kategori akibat kapitalisasi atau spasi.
"""

for col in cat_cols:
    df[col] = df[col].astype(str).str.lower().str.strip()

"""## Duplicate Handling
Data duplikat dihapus untuk menghindari bias analisis.
"""

print('Duplicate sebelum:', df.duplicated().sum())
df = df.drop_duplicates()
print('Duplicate sesudah:', df.duplicated().sum())

"""## **Outlier**
Metode IQR digunakan untuk mendeteksi nilai ekstrem tanpa asumsi distribusi normal.
"""

outlier_cols = ['Salary','Age']

for col in outlier_cols:
    if col in df.columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        df = df[(df[col] >= lower) & (df[col] <= upper)]

print('Jumlah data setelah outlier:', df.shape)

"""## **Construct Data**
Fitur Years_Working dibuat untuk mengetahui lama bekerja karyawan.
"""

if 'Join_Date' in df.columns:
    today = pd.to_datetime('today')
    df['Years_Working'] = (today - df['Join_Date']).dt.days / 365

"""Encoding performa dilakukan agar dapat dianalisis secara numerik."""

performance_map = {'poor':1,'average':2,'good':3,'excellent':4}

if 'Performance_Score' in df.columns:
    df['Performance_Num'] = df['Performance_Score'].map(performance_map)

"""## **Data Reduction**
Kolom yang tidak relevan seperti email dan phone dihapus.
"""

drop_cols = ['Email','Phone','Department_Region']
drop_cols = [col for col in drop_cols if col in df.columns]
df.drop(columns=drop_cols, inplace=True)

"""## **Save Dataset**"""

df.to_csv('/content/drive/MyDrive/tugas AVD/Messy_Employee_dataset.csv', index=False)
print('Dataset berhasil disimpan')

"""# **Checkpoint 4**

## **Load Dataset**
"""

df = pd.read_csv('/content/drive/MyDrive/tugas AVD/Messy_Employee_dataset.csv')
df.head()

"""## **Bar Chart**

**Jumlah Karyawan Berdasarkan Status**
"""

df.columns = df.columns.str.strip()

df.columns = df.columns.str.strip().str.replace(" ", "_")

plt.figure(figsize=(8,5))
df['Status'].value_counts().plot(kind='bar')

plt.title('Jumlah Karyawan Berdasarkan Status')
plt.xlabel('Status')
plt.ylabel('Jumlah Karyawan')

plt.show()

"""**Insight:**  
Grafik bar menunjukkan distribusi jumlah karyawan berdasarkan status pekerjaan. Dari visualisasi ini dapat dilihat bahwa sebagian besar karyawan berada pada status aktif dibandingkan dengan status lainnya.

**Action:**  
Perusahaan dapat menggunakan informasi ini untuk memantau kondisi tenaga kerja serta mengevaluasi tingkat retensi karyawan dalam organisasi.

## **Pie Chart**

**Proporsi Gender**
"""

status_counts = df['Status'].value_counts()

plt.figure(figsize=(6,6))
plt.pie(status_counts, labels=status_counts.index, autopct='%1.1f%%')

plt.title('Distribusi Status Karyawan')

plt.show()

"""**Insight:**  
Menunjukkan perbandingan jumlah karyawan berdasarkan gender.

**Action:**  
Perusahaan dapat mengevaluasi keberagaman tenaga kerja.

## **Line Chart**

**Salary Berdasarkan Experience**
"""

salary_by_age = df.groupby('Age')['Salary'].mean()

plt.figure(figsize=(8,5))
plt.plot(salary_by_age.index, salary_by_age.values, marker='o')

plt.title('Rata-rata Salary Berdasarkan Age')
plt.xlabel('Age')
plt.ylabel('Average Salary')

plt.show()

"""**Insight:**  
Semakin tinggi experience, salary cenderung meningkat.

**Action:**  
Pengalaman kerja bisa menjadi pertimbangan utama dalam sistem penggajian.

## **Histogram**

**Distribusi Usia**
"""

plt.figure(figsize=(8,6))
plt.hist(df['Age'], bins=10)

plt.title('Distribusi Usia Karyawan')
plt.xlabel('Age')
plt.ylabel('Frekuensi')

plt.show()

"""**Insight:**  
Menunjukkan sebaran usia karyawan.

**Action:**  
Berguna untuk perencanaan tenaga kerja di masa depan.

## **Box Plot**

**Salary Berdasarkan Department**
"""

plt.figure(figsize=(8,5))

sns.boxplot(x='Status', y='Salary_num', data=df)

plt.title('Distribusi Salary Berdasarkan Status')
plt.xlabel('Status')
plt.ylabel('Salary')

plt.show()

"""**Insight:**  
Box plot menunjukkan distribusi salary pada setiap status karyawan. Dari grafik ini dapat terlihat median salary, rentang distribusi, serta kemungkinan adanya outlier pada beberapa kategori status.

**Action:**  
Perusahaan dapat mengevaluasi struktur penggajian antar status karyawan untuk memastikan sistem kompensasi yang adil dan sesuai dengan tanggung jawab pekerjaan.

## **Scatter Plot**

**Age and Salary**
"""

plt.figure(figsize=(8,6))
sns.scatterplot(x='Age', y='Salary', data=df)

plt.title('Hubungan Age dan Salary')

plt.show()

"""**Insight:**  
Menunjukkan hubungan antara usia dan salary.

**Action:**  
Perusahaan dapat melihat faktor yang mempengaruhi salary.

## **Heatmap Korelasi**
"""

plt.figure(figsize=(10,8))

numerical = df.select_dtypes(include=['int64','float64'])

sns.heatmap(numerical.corr(), annot=True)

plt.title('Heatmap Korelasi Variabel Numerik')

plt.show()

"""
**Insight:**  
Menunjukkan hubungan antar variabel numerik.

**Action:**  
Membantu memahami faktor yang mempengaruhi salary atau performa.
"""